# Generated by Django 6.1.1 on 2026-09-05 09:46

import django.db.models.deletion
import personalization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0007_alter_cart_guest_id_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=personalization.models.personalization_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personalization', to='cart.cartitem')),
            ],
        ),
    ]
