# Generated by Django 6.1.1 on 2026-09-18 01:28

import django.db.models.deletion
import personalization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=personalization.models.personalization_photo_upload_path)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='personalization.personalization')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
