# Generated by Django 6.1.1 on 2026-09-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_courier_name_order_shipped_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='personalization_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
