# Generated by Django 6.1.1 on 2026-09-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderitem_personalization_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
