# Generated by Django 6.0.1 on 2026-02-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('background_color', models.CharField(default='#FF6B6B', max_length=20)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=20)),
            ],
        ),
    ]
