# Generated by Django 6.0.1 on 2026-02-17 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteannouncement',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='siteannouncement',
            name='text_color',
        ),
        migrations.AddField(
            model_name='siteannouncement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
