# Generated by Django 6.0.2 on 2026-02-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_filter_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
