# Generated by Django 6.0.1 on 2026-02-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.filter')),
            ],
            options={
                'unique_together': {('category', 'filter')},
            },
        ),
    ]
