# Generated by Django 6.0.1 on 2026-02-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_categoryfilter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategoryFilter',
        ),
    ]
